# This is a default config file for bottom.  All of the settings are commented
# out by default; if you wish to change them uncomment and modify as you see
# fit.

# This group of options represents a command-line flag/option.  Flags explicitly
# added when running (ie: btm -a) will override this config file if an option
# is also set here.



[flags]
# Whether to hide the average cpu entry.
hide_avg_cpu = true

# Whether to use dot markers rather than braille.
#dot_marker = false

# The update rate of the application.
rate = 1000

# Whether to put the CPU legend to the left.
left_legend = true

# Whether to set CPU% on a process to be based on the total CPU or just current usage.
#current_usage = false

# Whether to group processes with the same name together by default.
#group_processes = false

# Whether to make process searching case sensitive by default.
#case_sensitive = false

# Whether to make process searching look for matching the entire word by default.
#whole_word = false

# Whether to make process searching use regex by default.
#regex = false

# Defaults to Celsius.  Temperature is one of:
#temperature_type = "k"

#temperature_type = "f"
#temperature_type = "c"
#temperature_type = "kelvin"
#temperature_type = "fahrenheit"
#temperature_type = "celsius"
# The default time interval (in milliseconds).
default_time_value = 30000

# The time delta on each zoom in/out action (in milliseconds).
#time_delta = 15000

# Override layout default widget
#default_widget_type = "proc"

#default_widget_count = 1
# Use basic mode
#basic = false

# Use the old network legend style
#use_old_network_legend = false

# Remove space in tables
hide_table_gap = true

# Disable mouse clicks
#disable_click = false

# Built-in themes.  Valid values are "default", "default-light", "gruvbox", "gruvbox-light"
# color = "gruvbox"

# Show memory values in the processes widget as values by default
#mem_as_value = false

# Show tree mode by default in the processes widget.
tree = false


# These are all the components that support custom theming.  Note that colour support
# will depend on terminal support.

[colors]
table_header_color = "#f5e0dc"
all_cpu_color = "#f5e0dc"
avg_cpu_color = "#eba0ac"
cpu_core_colors = ["#f38ba8","#fab387","#f9e2af","#a6e3a1","#74c7ec","#cba6f7"]
ram_color = "#a6e3a1"
swap_color = "#fab387"
rx_color = "#a6e3a1"
tx_color = "#f38ba8"
widget_title_color = "#f2cdcd"
border_color = "#585b70"
highlighted_border_color = "#f5c2e7"
text_color = "#cdd6f4"
graph_color = "#a6adc8"
cursor_color = "#f5c2e7"
selected_text_color = "#11111b"
selected_bg_color = "#cba6f7"
high_battery_color = "#a6e3a1"
medium_battery_color = "#f9e2af"
low_battery_color = "#f38ba8"
gpu_core_colors = ["#74c7ec","#cba6f7","#f38ba8","#fab387","#f9e2af","#a6e3a1"]
arc_color = "#89dceb"

# Layout - layouts follow a pattern like this:
# [[row]] represents a row in the application.

# [[row.child]] represents either a widget or a column.

# [[row.child.child]] represents a widget.

#

# All widgets must have the type value set to one of ["cpu", "mem", "proc", "net", "temp", "disk", "empty"].
# All layout components have a ratio value - if this is not set, then it defaults to 1. 

# The default widget layout:

#[[row]]

#  ratio=30
#  [[row.child]]

#  type="cpu"

#[[row]]

#    ratio=40
#    [[row.child]]

#      ratio=4

#      type="mem"

#    [[row.child]]

#      ratio=3

#      [[row.child.child]]

#        type="temp"

#      [[row.child.child]]

#        type="disk"

#[[row]]

#  ratio=30
#  [[row.child]]

#    type="net"

#  [[row.child]]

#    type="proc"

#    default=true




# Filters - you can hide specific temperature and disks using filters.  This is admittedly a bit
# hard to use as of now, and there is a planned interface for managing this in the future:

#[disk_filter]

#is_list_ignored = false
#list = ["/dev/sda\\d+", "/dev/nvme0n1p2"]
#regex = true
#case_sensitive = false

#[temp_filter]
#is_list_ignored = false
#list = ["cpu", "wifi"]
#regex = false
#case_sensitive = false
